"""Advanced Sequence Preprocessing and Growth-Rate Analysis.

Adapted and enhanced with techniques from IntSeqBERT (Nakasho, 2026).
"""

from __future__ import annotations

import math
from typing import List, Optional, Sequence, Tuple, Union
import numpy as np


def compute_magnitude_4d_features(val: Union[int, float, str]) -> Tuple[float, float, float, float]:
    """Computes 4D magnitude representation: [log_val, sign_plus, sign_minus, sign_zero].

    - log_val: 1.0 + log10(|x|) for x != 0, else 0.0
    - sign_plus: 1.0 if x > 0 else 0.0
    - sign_minus: 1.0 if x < 0 else 0.0
    - sign_zero: 1.0 if x == 0 else 0.0

    Handles arbitrary-precision integers with overflow protection.
    """
    if isinstance(val, str):
        val = int(val)

    if val == 0:
        return 0.0, 0.0, 0.0, 1.0

    val_abs = abs(val)
    sign_plus = 1.0 if val > 0 else 0.0
    sign_minus = 1.0 if val < 0 else 0.0
    sign_zero = 0.0

    if isinstance(val_abs, int) and val_abs > 10**300:
        # Fallback for astronomical integers that exceed float64
        # Formula: log10(|x|) ~= len(str(|x|)) - 1, so 1.0 + (len - 1) = len
        log_val = float(len(str(val_abs)))
    else:
        log_val = 1.0 + math.log10(float(val_abs))

    return float(log_val), sign_plus, sign_minus, sign_zero


def analyze_log_linearity(
    sequence: Sequence[Union[int, float]], r2_threshold: float = 0.95
) -> Tuple[bool, float]:
    """Determines whether a sequence exhibits exponential (log-linear) growth.

    Fits linear regression on log10(|x_i|) vs index i. Returns (is_log_linear, r_squared).

    Args:
        sequence: Sequence terms.
        r2_threshold: R^2 correlation threshold (default 0.95).

    Returns:
        Tuple of (is_log_linear_bool, r2_score_float).
    """
    abs_values: List[float] = []
    indices: List[float] = []

    for i, val in enumerate(sequence):
        if val != 0:
            abs_values.append(float(abs(val)))
            indices.append(float(i))

    # Need at least 4 non-zero points to establish reliable log-linear trend
    if len(abs_values) < 4:
        return False, 0.0

    log_values = np.log10(abs_values)
    indices_arr = np.array(indices, dtype=np.float64)

    mean_x = float(np.mean(indices_arr))
    mean_y = float(np.mean(log_values))

    ss_tot = float(np.sum((log_values - mean_y) ** 2))
    if ss_tot < 1e-9:
        # Constant non-zero sequence
        return False, 0.0

    numerator = float(np.sum((indices_arr - mean_x) * (log_values - mean_y)))
    denominator_x = float(np.sum((indices_arr - mean_x) ** 2))

    if denominator_x < 1e-9:
        return False, 0.0

    slope = numerator / denominator_x
    intercept = mean_y - slope * mean_x

    # Ensure positive slope (growth) for exponential classification
    if slope <= 0.01:
        return False, 0.0

    y_pred = slope * indices_arr + intercept
    ss_res = float(np.sum((log_values - y_pred) ** 2))

    r_squared = float(1.0 - (ss_res / ss_tot))
    is_log_linear = r_squared >= r2_threshold

    return is_log_linear, r_squared


def check_finite_difference_polynomial_degree(
    sequence: Sequence[int], max_degree: int = 4
) -> Optional[int]:
    """Tests if a sequence is generated by a low-degree polynomial via iterated finite differences.

    If the d-th forward difference is constant and non-zero, returns polynomial degree d.
    """
    if len(sequence) < max_degree + 3:
        return None

    curr = [int(x) for x in sequence]
    for d in range(1, max_degree + 1):
        diff = [curr[i + 1] - curr[i] for i in range(len(curr) - 1)]
        if len(diff) < 3:
            break
        # Check if difference is constant
        if all(x == diff[0] for x in diff) and diff[0] != 0:
            return d
        curr = diff

    return None
